### PR TITLE
Organize the folder 

### PR DESCRIPTION
**Pull request by zxkjack123**
Major changes:
- Re-organize the folders
    - Put files of the previous test geometry (demo_collimator) into the folder `demo_collimator`.
    - Put FNG test related files to `FNG`

### CODE REVIEW

**Comment by pshriwise** [comment]
I'll take a look at this today. Thanks! I think a lot of the binary files we'll want to keep in a box folder somewhere. I can make one under ANL's account and share it with you if you're open to that.

**Comment by zxkjack123** [comment]
I am not sure whether I can access to that box, but we can try it.

**Comment by pshriwise** [comment]
I've (finally) created a shared folder on box for us to store larger, binary files instead of keeping them in this repo. Let me know if you didn't get access to it and I'll try again.

**Comment by zxkjack123** [comment]
@pshriwise I can access to it.

**Comment by pshriwise** [comment]
@zxkjack123 Excellent! Let's get any relatively large binary files like the `.h5m`'s moved into the box folder. Instead of maintaining them here, maybe we can write a script in this repo which will download the necessary files for testing and put them in an expected location within the repo. Does that sound alright?

**Comment by zxkjack123** [comment]
@pshriwise That's a good idea. We can download the big files when we need to use.

**Comment by zxkjack123** [comment]
Close this PR. I will open another PR with the latest updates.

**Pull request closed without merging**
