### PR TITLE
Adds the ATR model to the set of comparisons

### PR DESCRIPTION
**Pull request by pshriwise**

### CODE REVIEW

**Comment by zxkjack123** [comment]
Sorry for the late response. I find the link of the 'dagmc.h5m' file is absent in the 'README'. I need that 'dagmc.h5m' for the test.

**Comment by pshriwise** [comment]
Just added the link to the ATR model to the README. It's been added to the (recently renamed) `get_dagmc_models.sh` script as well.

**Comment by zxkjack123** [comment]
@pshriwise I failed to download the file after trying all the VPN tools (to unblock the Great Fire Wall). The tools which failed intermittently in the past are unavailable at all now. Which means, I can't access to google related tools. Can we use a separate repo to put the dagmc geometry data? Just like `pyne/data` for pyne.

**Comment by pshriwise** [comment]
Yeah! For sure. I'll setup a repo with Git LFS shortly.

**Comment by zxkjack123** [comment]
@pshriwise DAGMC geometry files got. No errors found for ATR model. By the way, do you have introduction documentations for ATR model?

**Pull request merged**
