### PR TITLE
Fng comp compare nps1e9

### PR DESCRIPTION
**Pull request by zxkjack123**
Changes:
- Rearranged folder, moved some documentation and big files to box
- Updated FNG input files and results
- Compare scripts

### CODE REVIEW

**Comment by zxkjack123** [comment]
@pshriwise Documentation and geometry files are moved to box. Now, this PR doesn't contain big files.

**Comment by pshriwise** [comment]
There are a couple of strange conflicts here, but otherwise I'm ready to merge this.

**Comment by zxkjack123** [comment]
Rebased on current master branch.

**Comment by pshriwise** [comment]
You’re back!

**Pull request merged**
